// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGBTja4HrDE-WiYpFmUMhcV4bsG65M5gs',
    appId: '1:286864240404:web:af2d715cc7242f66b29c01',
    messagingSenderId: '286864240404',
    projectId: 'ecodotdev-820a8',
    authDomain: 'ecodotdev-820a8.firebaseapp.com',
    storageBucket: 'ecodotdev-820a8.appspot.com',
    measurementId: 'G-BRV64PNC34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIeZ3JZ5itaNRwdxJa99xvAeafkJNI2RQ',
    appId: '1:286864240404:android:d96eff518b30ec9fb29c01',
    messagingSenderId: '286864240404',
    projectId: 'ecodotdev-820a8',
    storageBucket: 'ecodotdev-820a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ3on9lUmfpGdU0I6A8-2YlOeYD_Y22cs',
    appId: '1:286864240404:ios:dce9f1de6c4bc155b29c01',
    messagingSenderId: '286864240404',
    projectId: 'ecodotdev-820a8',
    storageBucket: 'ecodotdev-820a8.appspot.com',
    iosClientId: '286864240404-vbom9qru360mbatqom6upn40u56a5efg.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecodot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ3on9lUmfpGdU0I6A8-2YlOeYD_Y22cs',
    appId: '1:286864240404:ios:dce9f1de6c4bc155b29c01',
    messagingSenderId: '286864240404',
    projectId: 'ecodotdev-820a8',
    storageBucket: 'ecodotdev-820a8.appspot.com',
    iosClientId: '286864240404-vbom9qru360mbatqom6upn40u56a5efg.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecodot',
  );
}
